LIWC:
    path: "data/LIWC/LIWC2015_English.dic"
    cats_id:
        {
            1: "[FUNC]",
            30: "[AFFE]",
            40: "[SOCI]",
            50: "[COGP]",
            60: "[PERC]",
            70: "[BIOL]",
            80: "[DRIV]",
            100: "[RELA]",
            120: "[INFO]",
            110: "[WORK]",
            111: "[LEIS]",
            112: "[HOME]",
            113: "[MONE]",
            114: "[RELI]",
            115: "[DEAT]",
        }
LLM:
    model_name: "qwen2-72b-instruct"
    max_tokens: 1000
    temperature: 0
    presence_penalty: 1
    frequency_penalty: 1
    seed: 42
    api_key: sk-
    # tongyi_sso_ticket
    qwen:
        - 8178
        - xxx
    kimi:
        - 8179
        - xxx
    glm:
        - 8180
        - xxx
    spark:
        - 8181
        - xxx

OLLAMA:
    model_name: "qwen2.5:72b-instruct-q4_0"
    base_url: "http://192.168.28.5:11434"

OpenAIHK:
    api_key: "hk-"

MBTI:
    data_path: "data/MBTI/mbti.csv"
